import type { NextPage } from "next";
import Head from "next/head";

import { $getRoot, $getSelection } from "lexical";
import { useEffect } from "react";

import LexicalComposer from "@lexical/react/LexicalComposer";
import LexicalPlainTextPlugin from "@lexical/react/LexicalPlainTextPlugin";
import LexicalContentEditable from "@lexical/react/LexicalContentEditable";
import { HistoryPlugin } from "@lexical/react/LexicalHistoryPlugin";
import LexicalOnChangePlugin from "@lexical/react/LexicalOnChangePlugin";
import { useLexicalComposerContext } from "@lexical/react/LexicalComposerContext";

const theme = {
  ltr: "ltr",
  rtl: "rtl",
  placeholder: "editor-placeholder",
  paragraph: "editor-paragraph",
};

function onChange(editorState: any) {
  editorState.read(() => {
    const root = $getRoot();
    const selection = $getSelection();
    console.log(root, selection);
  });
}

function MyCustomAutoFocusPlugin() {
  const [editor] = useLexicalComposerContext();

  useEffect(() => {
    editor.focus();
  }, [editor]);

  return null;
}

function onError(error: any) {
  console.error(error);
}

const Editor: NextPage = () => {
  const initialConfig = {
    theme,
    onError,
  };

  return (
    <>
      <Head>
        <title>Lexical Editor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="border border-gray-500 mx-auto max-w-7xl mt-10 rounded">
        <LexicalComposer initialConfig={initialConfig}>
          <LexicalPlainTextPlugin
            contentEditable={<LexicalContentEditable />}
            placeholder={<div>Enter some text...</div>}
          />
          <LexicalOnChangePlugin onChange={onChange} />
          <HistoryPlugin />
          <MyCustomAutoFocusPlugin />
        </LexicalComposer>
      </div>
    </>
  );
};

export default Editor;
